[package]
name = "orca-seam"
version.workspace = true
edition.workspace = true

[dependencies]
orca-utils = { path = "../orca-utils" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true